# Generated by Django 4.2.3 on 2023-07-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="chats",
            fields=[
                ("chat_ID", models.AutoField(primary_key=True, serialize=False)),
                ("sender", models.CharField(max_length=20)),
                ("receiver", models.CharField(max_length=20)),
                ("message", models.CharField(max_length=1000)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
