# Generated by Django 4.2.3 on 2023-07-18 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="u_registration",
            name="dob",
            field=models.DateTimeField(verbose_name=datetime.date),
        ),
    ]
